# Site
name: "Njan Oru Malayali"
title: "ഞാൻ ഒരു മലയാളി"
description: "I am Sibeesh Venu, an Engineer by profession and writer by passion. My hobbies are blogging and photography. The motive of this website and YouTube channel is, to share the review of the places I visit. Your support is really appreciated, please click here (https://bit.ly/2wvG8eZ) to subscribe our YouTube channel"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo2.png'
baseurl: 'https://njan-oru-malayali.com'
google_analytics: 'UA-57404398-3'
disqus: 'sibeeshvenu'
mailchimp-list: 'SibeeshPassion'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sibeeshvenu:
    name: sibeeshvenu
    display_name: Sibeesh Venu
    gravatar: 4fa7268b7f35f84a7679f26cc076c7b3
    email: sibeesh.venu@gmail.com
    web: https://sibeeshpassion.com
    twitter: https://twitter.com/sibeeshvenu
    description: "I am Sibeesh Venu, an engineer by profession and writer by passion. Blogger, YouTuber, Photographer, Microsoft MVP"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-2685652658199360"
adsense-data-ad-slot: "8970675372"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
